################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/Components/lan8742 \
Drivers/BSP/STM32746G-Discovery \
Drivers/STM32F7xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
LWIP/App \
LWIP/Target \
Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Host_Library/Core/Src \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/system/OS \
TouchGFX/App \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/containers \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/intro_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/main_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/order_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/orderdetail_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/screen1_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/test_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__generated \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src/video \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/containers \
TouchGFX/build/MINGW32_NT-6.2/gui/src/intro_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/main_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/order_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/orderdetail_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/screen1_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/test_screen \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/intro_screen \
TouchGFX/generated/gui_generated/src/main_screen \
TouchGFX/generated/gui_generated/src/order_screen \
TouchGFX/generated/gui_generated/src/test_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/intro_screen \
TouchGFX/gui/src/main_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/order_screen \
TouchGFX/gui/src/test_screen \
TouchGFX/target \
TouchGFX/target/generated \
USB_HOST/App \
USB_HOST/Target \

